base_url = "https://darpalon.ir"
title = "Darpalon"
description = ""

output_dir = "docs"
compile_sass = true
minify_html = true

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "ayu-light"
render_emoji = true

[extra]
# Put all your custom variables here
